# Spring 数据源 (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sop_app?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: # Hibernate 属性，SQL 方言使得 Hibernate 为所选数据库生成更好的 SQL
  jackson:
    serialization:
      write-dates-as-timestamps: true